// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCj5g1pVeWW0U3LONguSAkUVd9uC9zff6Q',
    appId: '1:23911775316:web:e94dd185e5c28a4a8201c1',
    messagingSenderId: '23911775316',
    projectId: 'myapp-9f037',
    authDomain: 'myapp-9f037.firebaseapp.com',
    storageBucket: 'myapp-9f037.firebasestorage.app',
    measurementId: 'G-Q93S6K2S05',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1Mm4A-pxKd3HAI0bTeh7Nzb3ZlBKz2Uc',
    appId: '1:23911775316:android:ec8831ff4ea101ec8201c1',
    messagingSenderId: '23911775316',
    projectId: 'myapp-9f037',
    storageBucket: 'myapp-9f037.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAj4-brkZA7Fq-a-ObYw4ZedghzCscou00',
    appId: '1:23911775316:ios:854084f2173161b18201c1',
    messagingSenderId: '23911775316',
    projectId: 'myapp-9f037',
    storageBucket: 'myapp-9f037.firebasestorage.app',
    iosBundleId: 'com.example.authApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAj4-brkZA7Fq-a-ObYw4ZedghzCscou00',
    appId: '1:23911775316:ios:854084f2173161b18201c1',
    messagingSenderId: '23911775316',
    projectId: 'myapp-9f037',
    storageBucket: 'myapp-9f037.firebasestorage.app',
    iosBundleId: 'com.example.authApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCj5g1pVeWW0U3LONguSAkUVd9uC9zff6Q',
    appId: '1:23911775316:web:5371cc1692ceeb718201c1',
    messagingSenderId: '23911775316',
    projectId: 'myapp-9f037',
    authDomain: 'myapp-9f037.firebaseapp.com',
    storageBucket: 'myapp-9f037.firebasestorage.app',
    measurementId: 'G-XB32MHK7KE',
  );
}
